multiformats/go-multihash

sum_test.go
All of the other hash algorithms had test cases. Created two equivalent ones for SHA-3. Reference hashes were generated with http://emn178.github.io/online-tools/sha3_512.html and the tests still pass.
=> Added SHA-3 test cases

multihash/main.go, test/sharness/t0010-basics.sh
I think when -h or --help are passed, the exit code should be 0.
Also -h and --help should be displayed in the usage message.
This addresses some points I noted in issue https://github.com/jbenet/go-multihash/issues/18
=> main: add proper --help support

multihash.go, multihash_test.go
Resolves https://github.com/ipfs/go-ipfs/issues/2916
=> Use specific error when base58 didn't work

multihash.go, multihash_test.go, package.json, sum.go, sum_test.go
For some reason the ethereum crew decided to use a non-standardized hash function to base their entire system off of. This adds support for it.
=> add keccak256 for ethereum

multihash.go, multihash_test.go, sum.go, sum_test.go
No extra dependencies, as it's in the sha3 package. Closes #20
=> Added support for shake-128/256

multihash.go, sum.go, sum_test.go
Truncating to 32bits by default is a bit arbitrary and is guaranteed to make unsuspecting users very unhappy.
=> Set the default length of the ID hash function to -1

package.json, sum.go
=> use faster sha256 and blake2b implementations

multihash.go, package.json
An `encode(decode(x)) == x`:
1. Is 8-10x faster.
2. Does 6 allocations (3 on decode, 3 on encode) versus 238 (yes, that's per multihash decode + encode).
=> use a faster base58 library

multihash.go, multihash_test.go
to accommodate 0 length id (0x00) hashes.
Closes #69.
=> Change minimum length of multihash to 2 bytes

sum.go, sum_test.go
Towards https://github.com/ipfs/go-ipfs/issues/5019.
[Edit by kevina to avoid using words that will automatically close a bug in a different repo as this won't fix the bug until it a version with this fix is published and the gx dependency is updated in `go-ipfs`)
=> sum: check length of identity hash

opts/opts.go
=> include all hashes in algorithms list

.travis.yml, sum.go, sum_test.go
This adds the ability to register hash funcs independently and not required them in this library.
Note: this is a suggestion/WIP which can be refactored as needed.
This adds a map var which maps codecs to hash functions. The hash funcs must
have signature ~which accepts one byte slice, and returns one byte slice~ : `func(data []byte, length int) ([]byte, error)`.
It adds a RegisterHashFunc method which allows registration for any valid
codec. It prevents double registration or overwriting of hash funcs already
registered.
It also creates two funcs which are called by init() to register the funcs
which is already the current behaviour of the code:
* registerStdlibHashFuncs
* registerNonStdlibHashFuncs
If desired, the non-stdlib funcs can then easily be removed. Or it can be
implemented …
=> make multihash pluggable

multihash.go
Improve encoding performance by pre-allocating the buffer and thus avoiding un-needed allocations.
**system**
```
goos: darwin
goarch: amd64
go version: go1.11.5 darwin/amd64
Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
```
**benchcmp**
```
benchmark                          old ns/op     new ns/op     delta
BenchmarkEncode-8                  70.3          40.8          -41.96%
BenchmarkDecode-8                  70.4          72.1          +2.41%
BenchmarkSum-8                     78.9          79.6          +0.89%
BenchmarkBlake2B/blake2b-128-8     506           520           +2.77%
BenchmarkBlake2B/blake2b-129-8     512           506           -1.17%
BenchmarkBlake2B/blake2b-130-8     511           503           -1.57%
BenchmarkBlake2B/blake2b-255-8     552           516           -6.52% …
```
=> Small Encoding Performance Improvement

multihash.go, multihash_test.go
These were never used. Worse, other codecs have been allocated into this range
so they probably *can't* be used.
See: https://github.com/multiformats/multihash/issues/111
=> remove app codes

io_test.go, multihash.go, multihash_test.go, sum.go
To match the multicodec table and js-multihash
=> rename ID to IDENTITY

sum.go
These special-case functions don't allocate internally.
=> feat: reduce blake2b allocations by special-casing the 256/512 variants

multihash.go, multihash_test.go
* sha2-256-trunc254-padded
* poseidon-bls12_381-a2-fc1
Ref: https://github.com/multiformats/multicodec/pull/161
Ref: https://github.com/multiformats/multicodec/pull/171
Ref: https://github.com/multiformats/multicodec/pull/170
=> feat: add two filecoin hashes, without Sum() implementations

sum.go, sum_test.go
We register _codes_ for all lengths, but there's no reason to register _sum_ functions for all lengths. This change means we now correctly return "not supported" for unsupported lengths".
Also add a test to make sure sum never panics or returns a weird error.
=> fix: only register one blake2s length

opts/opts.go, sum.go
This provides a way to read from a stream instead of having to load a potentially large file into memory first.
Addresses issue #15
=> New SumStream function reads from io.Reader

core/magic.go, go.mod, go.sum, multihash.go, multihash_test.go, register/all/multihash_all.go, register/blake3/multihash_blake3.go, test/sharness/t0030-blake3.sh, test/sharness/t0030-lib/data.go
This PR registers the version of BLAKE3 hashing from https://github.com/lukechampine/blake3 which now seems to have vector optimization.
- Looks like an additional v1 version of cpuid is included -- concern?
- Sharness tests use the test data from the official Rust/C version at https://github.com/BLAKE3-team/BLAKE3
Closes https://github.com/multiformats/go-multihash/issues/121
=> Add blake3 hash and sharness tests

core/magic.go, core/registry.go
Corresponds to https://github.com/multiformats/multicodec/pull/234 .
Add these also to the automatically registered set, as we do for all the other hash functions that are readily available in the golang standard library.
=> Add variations of sha2

multihash.go, multihash_test.go, sum_test.go
Re-exporting blake3 constants in the right places so we can support it elsewhere (like go-verifcid, so that I can add support for approving fixed-length blake3 as a "good hash" there 😄 ) Draft because there are no tests yet.
edit: it doesn't exactly do this anymore, check comments below...
=> adding tests for blake3 and fixing an error handling bug.

core/magic.go, core/registry.go, multihash.go, register/blake3/multihash_blake3.go, sum.go, sum_test.go, version.json
=> variable hash functions testing

allocate_go119_test.go, allocate_go120_test.go, multihash.go, multihash_test.go, version.json
I took extra efforts for this to be a backward compatible change, I think `DecodedMultihash` should return a value struct not a pointer.
I also updated the error type to a value because this allows for 1 instead of 2 allocations when erroring.
```
name       old time/op    new time/op    delta
Decode-12     102ns ± 3%      18ns ± 3%   -82.47%  (p=0.000 n=9+9)
name       old alloc/op   new alloc/op   delta
Decode-12     64.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)
name       old allocs/op  new allocs/op  delta
Decode-12      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
```
I originally found this problem by benchmarking `go-cid`:
```
github.com/ipfs/go-cid.CidFromBytes
/home/hugo/go/pkg/mod/github.com/ipfs/go-cid@v0.4.0/cid.go
Total:      4.64GB    10.75GB (flat, cum) …
```
=> perf: outline logic in Decode to allow for stack allocations

multihash/README.md
gobuilder.me is dead, and it's only a matter of time before someone starts to distribute malware from this domain...
=> chore: we only support installing from source
